blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/muhittincamdali/iOS-Widget-Development-Kit#readme
    about: Check out the documentation first
  - name: ðŸ’¬ Discussions
    url: https://github.com/muhittincamdali/iOS-Widget-Development-Kit/discussions
    about: Ask questions and discuss ideas
